# Framework for running automated tests on Open Source Brain using Travis-CI.
# See https://github.com/OpenSourceBrain/osb-model-validation for more details

dist: xenial

addons:
  apt:
    packages:
       # Requirements for Neuron/OMV/etc
    - python-numpy
    - python-scipy
    - python-tornado
    - python-matplotlib
    - python-tk
    - python-dev

language: python
python:
     - "3.6"
     - "3.7"
     - "3.8"


env:
     - OMV_ENGINE=jNeuroML
     - OMV_ENGINE=jNeuroML_NEURON
     - OMV_ENGINE=jNeuroML_validate
     - OMV_ENGINE=NON_OMV_TESTS


#before_install:
    # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer) to imitate a display.
    #- "export DISPLAY=:99.0"
    #- "sh -e /etc/init.d/xvfb start"

install:
    # Required to run OMV tests
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    # NeuroML & main install
    - pip install pyNeuroML
    - pip install .
    # Add openworm bundle owmeta remote
    - owm bundle remote --user add ow-google-drive 'https://drive.google.com/uc?id=1NYAcKdcvoFu5c7Nz3l4hK5UacG_eD56V&authuser=0&export=download'

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - omv list -V
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - python setup.py install


    # Testing c302
    - cd c302
    - mkdir examples
    - python c302_IClamp.py A
    #- omv install NEURON # Need to install NEURON
    #- export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
    #- python runAndPlot.py -test
    #- python c302_utils.py -nogui

